apiVersion: v1
kind: Service
metadata:
  labels:
    app: ui-tourlist
  name: ui-tourlist-nodeport-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 31000
  selector:
    app: ui-tourlist
  type: NodePort
status:
  loadBalancer: {}
